doctrine:
    dbal:
        driver: sqlsrv
        host: '%env(resolve:GRID_MSSQL_HOST)%'
        port: '%env(resolve:GRID_MSSQL_PORT)%'
        dbname: '%env(resolve:GRID_MSSQL_DBNAME)%'
        user: '%env(resolve:GRID_MSSQL_USERNAME)%'
        password: '%env(resolve:GRID_MSSQL_PASSWORD)%'
        charset: 'UTF-8'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
