# Use this docker-compose file to host the site locally
version: '3.7'
services:
  nginx:
    image: milken/nginx-dev
    expose:
      - 80
      - 9222
    depends_on:
      - php
    links:
      - php
    volumes:
      - ".:/var/www"
    ports:
      - "80:80"
    env_file:
      - .env
      # - .env.local

  php:
    image: micaelaalvarez/php-events-api:latest
    expose:
      - '9000'
      - '4444'
    external_links:
      - solr-ssl_solr-network:milkensolr-nginx
    volumes:
      - ".:/var/www"
      - type: bind
        source: $HOME/.ssh
        target: /root/.ssh
        read_only: true
    links:
      - grid
    env_file:
      - .env

  redis:
    image: redis
    expose:
      - '6379'

  grid:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
          - ACCEPT_EULA=Y
    expose:
      - '1433'
    ports:
      - "1433:1433"

volumes:
  web: {}
  db: {}
